# Generated by Django 2.2 on 2022-05-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20220515_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='query',
            field=models.CharField(default='', max_length=200),
        ),
    ]
